pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		gradlePluginPortal()
		mavenCentral()
	}
	plugins {
		id 'fabric-loom' version "${fabric_loom_version}"
		id 'net.fabricmc.fabric-loom' version "${fabric_loom_version}" apply false
		id 'com.diffplug.spotless' version "${spotless_version}"
	}
}

rootProject.name = 'microdurability-unofficial'

include 'microdurability-core'
include 'microdurability-26.2'
include 'microdurability-dev-env-extras'
